# Generated by Django 4.2.10 on 2024-02-24 07:44

import django.core.validators
from django.db import migrations, models
import regular_exam_project.profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Username must be at least 3 chars long!'), django.core.validators.RegexValidator('^\\w+$', message='Username must contain only letters, digits, and underscores!')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('age', models.IntegerField(validators=[regular_exam_project.profiles.models.validate_age])),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=25)),
                ('profile_picture', models.URLField(blank=True)),
            ],
        ),
    ]
